# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1021, 674)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 92, 31))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.read_btn = QtWidgets.QPushButton(self.centralwidget)
        self.read_btn.setGeometry(QtCore.QRect(740, 70, 221, 31))
        self.read_btn.setObjectName("read_btn")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 70, 681, 551))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(120, 30, 491, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.open_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_btn.setGeometry(QtCore.QRect(620, 30, 61, 31))
        self.open_btn.setObjectName("open_btn")
        self.money_le = QtWidgets.QLineEdit(self.centralwidget)
        self.money_le.setGeometry(QtCore.QRect(740, 140, 111, 31))
        self.money_le.setObjectName("money_le")
        self.type_cb = QtWidgets.QComboBox(self.centralwidget)
        self.type_cb.setGeometry(QtCore.QRect(870, 140, 87, 31))
        self.type_cb.setObjectName("type_cb")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(740, 270, 221, 31))
        self.save_btn.setObjectName("save_btn")
        self.money_label = QtWidgets.QLabel(self.centralwidget)
        self.money_label.setGeometry(QtCore.QRect(740, 110, 91, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.money_label.setFont(font)
        self.money_label.setObjectName("money_label")
        self.type_label = QtWidgets.QLabel(self.centralwidget)
        self.type_label.setGeometry(QtCore.QRect(870, 100, 101, 41))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.type_label.setFont(font)
        self.type_label.setObjectName("type_label")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(740, 221, 221, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(740, 190, 91, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(700, 330, 296, 236))
        self.calendarWidget.setObjectName("calendarWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionCreate_File = QtWidgets.QAction(MainWindow)
        self.actionCreate_File.setObjectName("actionCreate_File")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionCreate_File)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CSV文件消费记录存储与查看—JustD2019"))
        self.label.setText(_translate("MainWindow", "文件内容"))
        self.read_btn.setText(_translate("MainWindow", "查看文件"))
        self.open_btn.setText(_translate("MainWindow", "浏览"))
        self.save_btn.setText(_translate("MainWindow", "存储"))
        self.money_label.setText(_translate("MainWindow", "消费金额"))
        self.type_label.setText(_translate("MainWindow", "消费类型"))
        self.label_2.setText(_translate("MainWindow", "消费日期"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionCreate_File.setText(_translate("MainWindow", "Create File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
